stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Building the project"
    - ls -al
    - pwd

job_test:
  stage: test
  script:
    - echo "Running tests"

job_deploy:
  stage: deploy